### ISSUE TITLE
No adapter with name 'sentiment/hinglish-twitter-sentiment@nirantk' was found in the adapter index.

### ISSUE THREAD

**Issue by whisere** [Adapter-Hub/Hub#27]
Hello, will you be able to help with this issue:
No adapter with name 'sentiment/hinglish-twitter-sentiment@nirantk' was found in the adapter index.

https://github.com/inception-project/inception-external-recommender/issues/28

Thanks!

**Comment by calpt** [comment]
Hi @whisere,

I tried to reproduce the error using the sample code from our website, i.e.:
```python
model = BertModelWithHeads.from_pretrained("bert-base-multilingual-uncased")
model.load_adapter("sentiment/hinglish-twitter-sentiment@nirantk", "text_task", config="pfeiffer")
```
but this runs without problems, so there doesn't seem to be a problem on our side. I'm not quite familiar with Inception but I'll try to see if there maybe is a problem with the integration.

**Comment by whisere** [comment]
Thank you very much @calpt I will look into Inception too, perhaps something to do with the other options, "text_task" and "pfeiffer" but I can't find them in inception, will keep looking. Thanks!

**Comment by whisere** [comment]
It seems this has been fixed at the Inception side. I will keep testing. How do we know the labels used in the Adapters? I can only find this adapter states they use 'postive, netural, negative' as tags in their description https://adapterhub.ml/explore/sentiment/hinglish-twitter-sentiment/ but not sure if the other Sentiment Analysis adapters also use 'netural' or have other tags? Thank you!

**Comment by calpt** [comment]
Great to hear. The labels of an adapter are determined by the task they're trained on, so looking up the respective task should give information about the label classes, e.g.:

SST-2: https://huggingface.co/datasets/glue#sst2
IMDb: https://huggingface.co/datasets/imdb
Rotten Tomatoes: https://huggingface.co/datasets/rotten_tomatoes

Unfortunately, not all adapters provide this information within their description currently, we're trying to improve that in the future.

**Comment by whisere** [comment]
Thank you so much!! That's very helpful!
