### ISSUE TITLE
Language Adapter for Italian Bert-Base-Multilingual-Cased

### ISSUE THREAD

**Issue by JoelNiklaus** [Adapter-Hub/Hub#38]
Hi,

I like the AdapterHub a lot, thanks for the great work!
My data is trilingual (German, French and Italian) and I am experimenting with bert-base-multilingual-cased.
I see that there are language adapters for German and French.
Would you mind uploading one for Italian as well similar to this one in German (https://adapterhub.ml/adapters/ukp/bert-base-multilingual-cased-de-wiki_pfeiffer/)?
I would greatly appreciate that!

Cheers,
Joel

**Comment by JoelNiklaus** [comment]
Also, later I would like to run experiments with XLM-Roberta-Base. Unfortunately, there is no language adapter available for French. I would greatly appreciate one for French similar to the one in German (https://adapterhub.ml/adapters/ukp/xlm-roberta-base-de-wiki_pfeiffer/). 
It would be great, if this could be added!

**Comment by calpt** [comment]
cc @JoPfeiff: do we have these adapters available for upload?
