### ISSUE TITLE
Adding adapters for CLIP - new model

### ISSUE THREAD

**Issue by NotNANtoN** [Adapter-Hub/Hub#41]
Hi, in my Master thesis I am currently working with fine-tuning CLIP on specific image-text datasets. Concretely, I am using the MIMIC-CXR dataset (https://physionet.org/content/mimic-cxr/2.0.0/).I'm training Adapters for the model and therefore I thought of possibly uploading them to AdapterHub! I think it would be a great addition to have the CLIP model available too, as we could then extend it as a community.

It seems like the main point would be to add the model architecture of the OpenAI CLIP model from here: https://github.com/openai/CLIP/blob/main/clip/model.py
I was planning on adding adapters to the `ResidualAttentionBlock`.

So I'm basically asking: is there interest for this model? If so, I would gladly try to contribute this, but I might need some help as I am not super familiar with AdapterHub yet. If there are some instructions of how I could best add a new model that would be amazing.

**Comment by calpt** [comment]
Duplicate of https://github.com/adapter-hub/adapter-transformers/issues/296
