### ISSUE TITLE
Getting Check Error while Uploading Pre-trained Adapters

### ISSUE THREAD

**Issue by kabirahuja2431** [Adapter-Hub/Hub#47]
Hello,

I have been trying to upload some pre-trained adapters for XNLI task. I am seeing the following error in the file format check in the install step:

> ERROR: Cannot install -r scripts/requirements.txt (line 5) and pyyaml because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
>     The user requested pyyaml
>     adapter-transformers 3.1.0a0 depends on pyyaml>=5.1
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 

I am not sure if there is something wrong with my yaml file, since it does pass the tests when I test it through adapter-hub-cli:
`adapter-hub-cli check adapters/kabirahuja2431/bert-base-multilingual-cased_nli_MultiNLI_adapter_config.yaml`

Appreciate any help on this. Thanks!

**Comment by calpt** [comment]
Hey @kabirahuja2431, thanks for bringing this up. The error you show is indeed caused by issues in our GH Actions workflows and not your yaml file. I just fixed those and merged the fix back into your PR branch.

**Comment by kabirahuja2431** [comment]
Great! Thank you.
