### ISSUE TITLE
✘ Failed to pack adapter 'config_id'

### ISSUE THREAD

**Issue by bhavitvyamalik** [Adapter-Hub/Hub#50]
While packing adapter I got this error `✘ Failed to pack adapter 'config_id'`. What exact problem is happening here?

I have one more question, if I have to upload 60+ adapters, is there any way I can automate this whole process?

**Comment by calpt** [comment]
This repository is no longer maintained, please contribute adapters as described in: https://docs.adapterhub.ml/huggingface_hub.html. Thank you!
